### ISSUE TITLE
Does this repo support the segmentation of Davis2017?

### ISSUE THREAD

**Issue by Starboy-at-earth** [dzh19990407/LBDT#7]
Thank you for your great works. Your reply is desired!!!

**Comment by dzh19990407** [comment]
Thank you for your attention! Unfortunately, the converted annotation files have been lost in the old servers. You can download the annotation file on [Refer-DAVIS official website](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/video-segmentation/video-object-segmentation-with-language-referring-expressions) and reorganize them into the same format as those of A2D-Sentences dataset.

**Comment by Starboy-at-earth** [comment]
@dzh19990407 Just adapt the following script?
##################################################
import os

video_root = clips320H'
frame_root = '/frames'

video_list = os.listdir(video_root)
total_videos = len(video_list)
for idx, video_name in enumerate(video_list):
    video_path = os.path.join(frame_root, video_name[:-4])
    if not os.path.exists(video_path):
        os.mkdir(video_path)
    is_success = os.system('ffmpeg -i {} -f image2 {}/%05d.jpg'.format(os.path.join(video_root, video_name),
                                                                      video_path))
    print(idx, '/', total_videos, video_name, is_success)

**Comment by Starboy-at-earth** [comment]
@dzh19990407 Could you plz contact me in the following email? 2667004002@qq.com. I, if I have the fortune, wish to consult some details of LBDT....
